Repo tuneup
bitwarden/authenticator-android pull request #112
Opened 2024-05-31 21:02 UTC by withinfocus

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-05-31 21:19 UTC, SaintPatrck requested changes

2024-05-31 21:19 UTC, SaintPatrck commented on .github/workflows/build.yml
> +        run: bundle exec fastlane test
This needs to align with the `fastfile` lane names: 
https://github.com/bitwarden/authenticator-android/blob/main/fastlane/Fastfile#L21

2024-05-31 21:19 UTC, SaintPatrck commented on .github/workflows/test.yml
> +            ${{ github.workspace }}/build-cache
We should cache build output separately from the gradle cache. I usually key build output cache on the commit hash to make sure it's always restoring the last build. If we key it on these file hashes it's not going to update after builds unless a gradle dependency changes.

```
      - name: Cache build output
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: |
            ${{ github.workspace }}/build-cache
          key: ${{ runner.os }}-build-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-
```

If we are or become concerned with cache sizes, we can be more aggressive about how often they're purged. I believe the default is 15 days.

2024-05-31 21:32 UTC, SaintPatrck approved these changes

2024-06-03 14:15 UTC, vgrassia approved these changes

2024-06-03 14:17 UTC, merged