BITAU-76 Update copy on download Bitwarden action card
bitwarden/authenticator-android pull request #260
Opened 2024-10-29 18:19 UTC by ahaisting-livefront

## 🎟️ Tracking

https://livefront.atlassian.net/browse/BITAU-76

## 📔 Objective

Simple copy update that came back from QA!

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-10-29 22:01 UTC, SaintPatrck requested changes
We should ignore `ExtraTranslation` lint error. Crowdin will manage the translation files. You only need to remove the old entry and add the new one to the `main/res` strings.

Recently had to do the same in PM: https://github.com/bitwarden/android/pull/4176

2024-10-29 22:04 UTC, SaintPatrck commented
Opened #262

2024-10-30 13:20 UTC, ahaisting-livefront commented
Nice callout!! Rebased with `main` and removed the other string file updates.

2024-10-30 15:00 UTC, SaintPatrck approved these changes

2024-10-30 15:06 UTC, merged