Assemble, sign, upload and publish release builds
bitwarden/authenticator-android pull request #38
Opened 2024-04-18 19:08 UTC by SaintPatrck

## 🎟️ Tracking

N/A

## 📔 Objective

Build signed release APK's for uploading and publishing.

Version code and name are derived based on the latest version information from Firebase. Version codes are incremented on each publication. Version name is derived from the current year, date, and latest published release's revision number.

Prod variants are published to Firebase from `master` branch. Firebase publication uses the last commit message as the release notes.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-04-20 18:14 UTC, KatherineInCode submitted a review, later dismissed

2024-04-22 15:15 UTC, mimartin12 requested changes
Just some linting changes.

I did notice that there are some uses of `shell: bash`, but the runner is Ubuntu, which already defaults to Bash. Up to you if you want to remove it though.

2024-04-22 16:54 UTC, mimartin12 approved these changes
Works with me!

2024-04-22 17:48 UTC, KatherineInCode approved these changes

2024-04-22 17:49 UTC, merged